const express = require('express');
const cors = require('cors');
const fs = require('fs-extra');
const path = require('path');
const multer = require('multer');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(express.static('.'));

// Configure multer for file uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'assets/');
  },
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    cb(null, file.fieldname + '-' + uniqueSuffix + path.extname(file.originalname));
  }
});

const upload = multer({ 
  storage: storage,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB limit
  fileFilter: (req, file, cb) => {
    const allowedTypes = /jpeg|jpg|png|gif|pdf/;
    const extname = allowedTypes.test(path.extname(file.originalname).toLowerCase());
    const mimetype = allowedTypes.test(file.mimetype);
    
    if (mimetype && extname) {
      return cb(null, true);
    } else {
      cb(new Error('Only images and PDFs are allowed'));
    }
  }
});

// Helper function to read data files
async function readDataFile(filename) {
  try {
    const filePath = path.join(__dirname, 'data', filename);
    const content = await fs.readFile(filePath, 'utf8');
    // Remove the variable declaration and export to get clean JSON
    const cleanContent = content
      .replace(/^const\s+\w+\s*=\s*/, '')
      .replace(/;\s*$/, '')
      .replace(/if\s*\(typeof\s+module\s*!==\s*'undefined'\s*&&\s*module\.exports\)\s*{\s*module\.exports\s*=\s*\w+;\s*}/g, '');
    
    return JSON.parse(cleanContent);
  } catch (error) {
    console.error(`Error reading ${filename}:`, error);
    throw error;
  }
}

// Helper function to write data files
async function writeDataFile(filename, data) {
  try {
    const filePath = path.join(__dirname, 'data', filename);
    const variableName = filename.replace('.js', '').replace('-', '');
    
    let content = `// ========================================\n`;
    content += `// ${filename.toUpperCase().replace('.JS', '')} DATA\n`;
    content += `// ========================================\n`;
    content += `// Auto-generated by admin panel\n\n`;
    content += `const ${variableName} = ${JSON.stringify(data, null, 2)};\n\n`;
    content += `// Export for use in other files\n`;
    content += `if (typeof module !== 'undefined' && module.exports) {\n`;
    content += `  module.exports = ${variableName};\n`;
    content += `}\n`;
    
    await fs.writeFile(filePath, content, 'utf8');
    return true;
  } catch (error) {
    console.error(`Error writing ${filename}:`, error);
    throw error;
  }
}

// Routes

// Get all data
app.get('/api/data/:filename', async (req, res) => {
  try {
    const { filename } = req.params;
    const data = await readDataFile(filename);
    res.json({ success: true, data });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Save data
app.post('/api/data/:filename', async (req, res) => {
  try {
    const { filename } = req.params;
    const { data } = req.body;
    
    await writeDataFile(filename, data);
    res.json({ success: true, message: `${filename} updated successfully` });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Upload file
app.post('/api/upload', upload.single('file'), (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, error: 'No file uploaded' });
    }
    
    const fileUrl = `./assets/${req.file.filename}`;
    res.json({ 
      success: true, 
      message: 'File uploaded successfully',
      fileUrl: fileUrl,
      filename: req.file.filename
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Get file list
app.get('/api/files', async (req, res) => {
  try {
    const assetsPath = path.join(__dirname, 'assets');
    const files = await fs.readdir(assetsPath);
    const fileList = files.map(file => ({
      name: file,
      path: `./assets/${file}`,
      size: fs.statSync(path.join(assetsPath, file)).size
    }));
    
    res.json({ success: true, files: fileList });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Delete file
app.delete('/api/files/:filename', async (req, res) => {
  try {
    const { filename } = req.params;
    const filePath = path.join(__dirname, 'assets', filename);
    
    await fs.remove(filePath);
    res.json({ success: true, message: 'File deleted successfully' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});


// Serve main portfolio
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// Error handling middleware
app.use((error, req, res, next) => {
  if (error instanceof multer.MulterError) {
    if (error.code === 'LIMIT_FILE_SIZE') {
      return res.status(400).json({ success: false, error: 'File too large. Maximum size is 5MB.' });
    }
  }
  res.status(500).json({ success: false, error: error.message });
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 Portfolio server running on http://localhost:${PORT}`);
  console.log(`🌐 Portfolio available at http://localhost:${PORT}`);
});

module.exports = app;

